[testing]
  template="./templates/support-notification.tmpl"
  images=["./images/Page-1.png","./images/email-template-illustration.png","./images/facebook.png","./images/twitter.png","./images/linkedin.png"]
[testingTesting]
  subject="Thanks for using our service || MetaSecure"
  images=["./images/Page-1.png","./images/email-template-illustration.png","./images/facebook.png","./images/twitter.png","./images/linkedin.png"]
[testingxenon]
  subject="Thanks for using our service || MetaSecure"
  template="./templates/support-notification.tmpl"
[userNotification]
  subject="Thanks for contacting us || MetaSecure"
  template="./templates/user-notification.tmpl"
  images=["./images/Page-1.png","./images/email-template-illustration.png","./images/facebook.png","./images/twitter.png","./images/linkedin.png"]